### ISSUE TITLE
Add documentations

### ISSUE THREAD

**Issue by ali4heydari** [siyanew/grpcson#1]
Hi @siyanew,
I can't find any documentation for this repo. Please add documentations.
Thanks for making GitHub better. ❤️

**Comment by SeyedAlirezaFatemi** [comment]
@ali4heydari is right. Documentations can be really helpful. Please add documentations.

**Comment by ali4heydari** [comment]
@siyanew Did you get a chance to add documentations? 👀

**Comment by ali4heydari** [comment]
Any progress?

**Comment by siyanew** [comment]
@ali4heydari @SeyedAlirezaFatemi Code and Documentation are ready now.
